target("dhrystone")
	set_kind("binary")
	set_languages("c89", "c++23")

	add_files("dry.c", "main.cpp")
	add_files("$(projectdir)/template/loaded-linkscript.ld")
	add_defines("DHRYSTONE")
	add_includedirs("$(projectdir)")
	add_cflags("-fno-function-sections -fno-data-sections", "-DPASS2", "-DTIME")
	add_deps("platform-v1", "loaded-runtime")
