target("boot.stage0")
	set_kind("static")
	add_files("startup/stage0.S")

target("boot.stage1")
	set_kind("static")
	add_files("startup/stage1.S")

rule("link.include")
	on_load(function (target)
		target:add("ldflags", "-L$(projectdir)/boot/linkerscript/include")
	end)
rule_end()

rule("link.stage0")
	on_load(function (target)
		target:add("files", "$(projectdir)/boot/linkerscript/stage0.ld")
	end)
	add_deps("link.include")
rule_end()

rule("link.stage0-memlimit")
	on_load(function (target)
		target:add("files", "$(projectdir)/boot/linkerscript/stage0-memlimit.ld")
	end)
	add_deps("link.include")
rule_end()

rule("link.stage1")
	on_load(function (target)
		target:add("files", "$(projectdir)/boot/linkerscript/stage1.ld")
	end)
	add_deps("link.include")
rule_end()